-- Migration: Add playwright_test_executions table
-- Run this against your existing SQLite database

CREATE TABLE IF NOT EXISTS playwright_test_executions (
    id TEXT PRIMARY KEY,
    persona_id TEXT NOT NULL,
    website_id TEXT NOT NULL,
    run_id TEXT,                          -- optional link to existing test_runs
    url TEXT NOT NULL,
    dom_snapshot TEXT,                    -- cleaned HTML DOM fetched before script generation
    generated_script TEXT NOT NULL,       -- the JS Playwright script generated by LLM
    browser_name TEXT DEFAULT 'chromium',
    status TEXT DEFAULT 'pending',        -- pending | running | success | error
    execution_log TEXT,                   -- JSON array of log lines
    error_message TEXT,
    screenshot_base64 TEXT,              -- final or error state screenshot
    duration_ms INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME,
    FOREIGN KEY (persona_id) REFERENCES personas(id),
    FOREIGN KEY (website_id) REFERENCES websites(id)
);

CREATE INDEX IF NOT EXISTS idx_playwright_executions_persona
    ON playwright_test_executions(persona_id);

CREATE INDEX IF NOT EXISTS idx_playwright_executions_website
    ON playwright_test_executions(website_id);

CREATE INDEX IF NOT EXISTS idx_playwright_executions_status
    ON playwright_test_executions(status);

CREATE INDEX IF NOT EXISTS idx_playwright_executions_created
    ON playwright_test_executions(created_at DESC);
